### PR TITLE
Xcode7 Support

### PR DESCRIPTION
**Pull request by briancroom**
Hey folks, the time has come to finally see about getting this merged into master. I have rebased this as a new branch because I managed to botch merging master into the long-lived Xcode7 branch a while back, and didn't want to deal with figuring out how to resolve that mess.

In addition to the great work that @tjarratt and pairs did over the course of the summer to get the Xcode 7 support bootstrapped and to fix some of the symbolication issues, I have now done a bunch of additional cleanup to try to get things in good shape. This includes:
* Use a build-time environment variable to more dynamically determine the path to the `atos` tool
* Update the test bundle specs so that they do the appropriate checks on both Xcode 6 and 7
* Remove the "OSX Failing Test Bundle" target because it didn't seem to be providing value anymore
* Refactor the test bootstrapping code a bit to greatly improve code sharing between spec suite and spec bundle execution

At this point, `rake` passes on my workstation when building with Xcode 7 GM, and Travis should be passing, although it is not using Xcode 7 yet. There are some extra issues related to the Travis build being discussed at #345.

Please give it a whirl and let me know if there are any critical issues that would prevent us from getting this merged in!

(Pinging some people who have been involved in the discussion at #333: @akitchen @tjarratt @alexbasson @joemasilotti @mjstallard)

### CODE REVIEW

**Comment by tjarratt** [comment]
Thanks so much for taking the time to clean this up and make this easier to maintain, @briancroom! This looks great.

**Comment by adamhrz** [comment]
@briancroom This is merged into master now - is xcode7 branch still relevant or should we use master for xcode 7 builds?

**Comment by briancroom** [comment]
@adamhrz The `master` branch now contains the latest code for both Xcode 6 and 7.

@tjarratt Do you think we should just go ahead and delete the long-lived Xcode7 branch now?

**Comment by tjarratt** [comment]
Deleting that branch will cause anyone using it to realize that something that changed, so it seems reasonable to delete it so no one continues to rely on it. I'm for deleting it.

**Comment by adamhrz** [comment]
@briancroom @tjarratt Do you know when PivotalCoreKit will update to the XCode 7 version of Cedar?

**Comment by briancroom** [comment]
@adamhrz There is a PR open at https://github.com/pivotal/PivotalCoreKit/pull/156 which I need to revisit and update a bit now that the Cedar's Xcode 7 work has been merged.

**Comment by adamhrz** [comment]
@briancroom thanks for the update. Do you think we're looking at 2 weeks, a month or longer as a timeframe? Trying to plan our own migration and since we use Cedar and Pivotal we're trying to decide if we it's worth a local patch in the short term

**Comment by briancroom** [comment]
I'm thinking it shouldn't be too long - definitely within 2 weeks unless unforeseen difficulties arise.

**Pull request merged**
