### PR TITLE
Fixup header visibility

### PR DESCRIPTION
**Pull request by briancroom**
This takes the work that @idoru started in #315 and updates it for the current state of the `master` branch. It accomplishes a few goals:

* Ensure the `NSMethodSignature` and `NSInvocation` categories aren't publicly exposed
* Add `cdr_` prefixes to category methods so we aren't risking conflicts
* Reorganize header files on disk to reflect the `public`/`project` division
* Make sure that both the framework targets and the podspec only expose the appropriate public headers

Once this is in, I think we will be in a good spot regarding what we are exposing and what is hidden, across all our distribution mechanisms.

CC @akitchen @tjarratt

### CODE REVIEW

**Comment by briancroom** [comment]
@tjarratt and I were talking about this yesterday and we are pretty happy about it. I would love to get any feedback from @idoru before merging though!

**Comment by akitchen** [comment]
👍🏾

Thanks everyone for tidying this up

**Comment by tjarratt** [comment]
:+1: hiding the NSInvocation category header was a huge win.

**Comment by briancroom** [comment]
Since I was the one who made that header public in the first place, it was about time I clean that up :)

**Comment by tjarratt** [comment]
We're all just trying to make the world a better place.

Really glad you found the time for this PR, I was really struggling to make time for this lately.

**Comment by idoru** [comment]
Thanks @briancroom for following through!

I tried it out on a few different projects and it looks good to me.

**Pull request merged**
