### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by younata**
solving https://github.com/pivotal/cedar/issues/328

Push a tag after this is merged, then Carthage will automatically pick up the latest release.

### CODE REVIEW

**Comment by akitchen** [comment]
Thanks for taking this on @younata 

Quick question for the group - shouldn't the Info.plist for this target reflect the tagged version?  Or something?

**Comment by akitchen** [comment]
Unfortunately the spec suites don't build with these changes.  

```
duplicate symbol _CDRVersion in:
    /Users/travis/build/pivotal/cedar/derivedData/Build/Intermediates/Cedar.build/Release-iphonesimulator/Cedar iOS XCTest Tests.build/Objects-normal/x86_64/ObjCHeadersSpec.o
    /Users/travis/build/pivotal/cedar/build/Release-iphonesimulator/libCedar-StaticLib.a(CDRFunctions.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Also reproduces when running specs via rake

**Comment by younata** [comment]
Oops.

**Comment by younata** [comment]
@akitchen This will break things on existing installs, by the way. All to get rid of that pesky import warning when trying to use the Cedar dynamic framework.

**Pull request closed without merging**
