### PR TITLE
Ensure project/private headers aren't included in frameworks.

### PR DESCRIPTION
**Pull request by idoru**
Also organized headers on filesystem so it is easier to see which headers should be private vs. scoped to the project.

### CODE REVIEW

**Comment by jeffh** [comment]
Hey @idoru, just update the pull request to have the cocoapods spec file to only include public headers.

**Comment by idoru** [comment]
We had to add NSInvocation+Cedar.h back in, since -[arguments] is referred to by HaveReceived.h in failure_message_end()

I feel like we still should be able to bury this in an implementation and get rid of the import, WDYT @jeffh ?

**Comment by jeffh** [comment]
I'd prefer that @idoru.

**Comment by akitchen** [comment]
I think we should revisit this after #332 is merged

**Comment by pivotal-brian-croom** [comment]
Now that the iOS dynamic framework has been merged we should make sure we take a close look at the visibility of all the headers, and make sure that the same visibility has been set for both the Mac and iOS frameworks. On `master` right now, there are a bunch of discrepancies between the frameworks on the two platforms.

**Comment by briancroom** [comment]
Since #350 was merged, which already incorporated these changes, I'm closing this PR.

**Pull request closed without merging**
