### PR TITLE
Replaced custom iOS Cedar framework and static lib with normal iOS frame...

### PR DESCRIPTION
**Pull request by jeffh**
Breaking change for users. Import path is always <Cedar/Cedar.h>.

Both Mac and iOS frameworks now also utilize 'Cedar' as the
product/module name. Renamed schemes, targets, and rakefile tasks to be
more indicative of their corresponding platforms:

 - targets/schemes: Postfix 'OS X' to mac schemes if missing
 - rakefile: uispecs => ios_specs
 - rakefile: specs => osx_specs
 - rakefile: constants renames

Fixed rakefile's retry mechanism for running ios-sim to only when
ios-sim fails to bootstrap the simulator.

Deleted dead code: CDROTestReporter.

The new iOS framework should work with previous runtimes (eg - iOS 7.1,
7.0.1) as long as it is built with the latest runtimes (8+) Although a
warning about running iOS frameworks on older runtimes is emitted by
xcode, it is a linker-time warning. This means warnings-as-errors will
not promote it to an error.

[finishes #85837504, #85844134]

### CODE REVIEW

**Comment by AlexDenisov** [comment]
There is no static framework anymore, am I correct?

**Comment by jeffh** [comment]
In this PR, yes. Although it could be left in if it's still preferred. I'm not strongly opinionated to one way or the other.

**Comment by AlexDenisov** [comment]
Well, personally I prefer static frameworks. But let's see what community prefers more.

**Comment by akitchen** [comment]
<bikeshed>This is super minor, but I think I would prefer we use osx
instead of mac.</bikeshed>

**Comment by jeffh** [comment]
Oops, I forgot to update the commit message. I'll amend it.

**Comment by idoru** [comment]
I tried to use this and failed; but maybe I'm computering it wrong.

I first tried rake install, which brings up a dialog asking if I want to allow code-signing. Is this required when making universal frameworks?

If allowed to code-sign, the script fails later because it's trying to copy `/Users/pivotal/workspace/Cedar/build/Release-iphoneuniversal/Cedar iOS.framework` but this isn't present. It looks like the correct paths are `/Users/pivotal/workspace/Cedar/build/Release-iphoneos/Cedar.framework` and `/Users/pivotal/workspace/Cedar/build/Release/Cedar.framework` for iOS and OS X respectively.

So, next, I tried to create a project and added Cedar as a submodule. I added Cedar.framework as target dependency as well as linking the target to Cedar.framework, but it fails to find headers without explicitly setting search paths. Is there a trick to setting up cross project framework dependencies properly?

**Comment by wileykestner** [comment]
That code signing thing might be because your build destination is for a
device - if you build for simulator, it shouldn't prompt you.  Not sure
about the other stuff.

**Comment by jeffh** [comment]
Closing PR. There seems to be some problems with modules + frameworks.

A future pull request that also includes static libs and frameworks would be ideal. There might need to be same internal refactors for this.

**Pull request closed without merging**
